ISSUE5 - Implemented transactions table
Seavus/fikt-24-25 pull request #29
Opened 2024-12-25 22:40 UTC by Emanuela-Chavleska

2024-12-26 09:35 UTC, Igor-Kostov requested changes
Create shared/reusable "Table" component with @Inputs
Transactions Component should be moved to "features" folder
Move hardcoded values: "displayedColumns" & "dataSource" to transaction component and send them to shared "Table" component

2024-12-26 14:14 UTC, krenardrala-qinshift commented on budget-manager-client/src/app/shared/components/transactions/transactions.component.html
Please change the name of the component to something more general, because this is only a wrapper component for the table. For example: custom-table, ngx-table, etc.
Also update the code to dynamically generate the table columns based on the input parameter: displayedColumns.

2024-12-26 14:16 UTC, krenardrala-qinshift commented on budget-manager-client/src/app/app.module.ts
Please remove module file, with newer versions of Angular it is recommended to use standAlone components. Add the imports directly in the app.comonent.ts

2024-12-26 14:16 UTC, krenardrala-qinshift commented on budget-manager-client/src/app/shared/components/transactions/transactions.component.scss
Please use scss best practices, like nesting the selectors

2025-01-20 13:33 UTC, krenardrala-qinshift commented on budget-manager-client/src/app/app.component.html
> +<app-transactions></app-transactions>
Do not add the component here yet, we will use the table component in other pages

2025-01-20 13:33 UTC, krenardrala-qinshift commented on budget-manager-client/src/app/app.component.ts
> +  imports: [ SidebarComponent, CommonModule, ButtonComponent, TransactionsComponent],
Remove TransactionsComponent from app.component

2025-01-20 13:35 UTC, krenardrala-qinshift commented on budget-manager-client/src/app/shared/components/wrapper-table/wrapper-table.component.ts
> +  @Input() dataSource: any[] = [];
Please avoid using "any", instead define a type for the dataSoruce

2025-01-23 12:12 UTC, krenardrala-qinshift approved these changes

2025-01-23 12:14 UTC, merged